export enum Field {
  TASK_NAME = 'TASK_NAME',
  TASK_REF = 'TASK_REF',
  TASK_LOT = 'TASK_LOT',
  TASK_MANUFACTURER = 'TASK_MANUFACTURER',
  TASK_PURCHASE_DATE = 'TASK_PURCHASE_DATE',
  TASK_SERIES_CODE = 'TASK_SERIES_CODE',
  ID = 'ID',
  FIRST_NAME = 'FIRST_NAME',
  LAST_NAME = 'LAST_NAME',
  USERNAME = 'USERNAME',
  EMAIL = 'EMAIL',
  STATUS = 'STATUS',
  LOCKED = 'LOCKED'
}
